src/blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    detail_blog_view,
    # edit_blog_view,

)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),




]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from personal.views import (
    home_screen_view,
)
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,

)
from team.views import (
    create_team_view,
    contact_us_view,
)

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),
    path('create_team/', create_team_view, name="create_team"),
    path('contact_us/', contact_us_view, name="contact_us"),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/personal/models.py
from django.db import models

# Create your models here.

src/personal/views.py
from django.shortcuts import render
from operator import attrgetter
from blog.views import get_blog_queryset
from blog.models import BlogPost

# Create your views here.

def home_screen_view(request):

    context = {}

    query = ""
    if request.GET:
        query = request.GET['q']
        context['query'] = str(query)

    blog_posts = sorted(get_blog_queryset(query), key=attrgetter('date_updated'), reverse = True)
    context['blog_posts'] = blog_posts


    return render(request, "personal/home.html", context)

src/personal/templates/personal/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<style type="text/css">
  @media(max-width: 768px){
      .right-column{
          margin-left: 0px;
      }
  }
   @media(min-width: 768px){
      .right-column{
          margin-left: 20px;
      }
  }
  .blog-post-container{
      margin-bottom:    20px;
      width:            100%;
  }
  .create-post-bar{
      background-color: #fff;
      margin-bottom:    20px;
  }
  .left-column{
      padding: 0px;
  }
  .right-column{
      padding: 0px;
      margin-top: 50px;
  }
  .lead{
    font-size: 17px;
  }
</style>
<div class="container">
  <div class="row">
    <!--Blog feed-->
    <div class="left-column col-lg-7 offset-lg-1">
      <!--End Top create post bar-->
      <div class="d-lg-none mb-3">
        <div class="card m-auto d-flex flex-column p-3">
          <img class="img-fluid d-block m-auto pb-2" src="{% static 'logo.png' %}" width="72" height="72">
          <p class="lead">To write a post:</br>
          Log in to our Website.</br>
          Click the ‘Create Post’ tab.</br>
          Start filling in the blanks: enter your post title in the upper field, and enter your post body content in the main post editing box below it.
          As needed, select a category, add tags, and make other selections from the sections below the post. (Each of these sections is explained below.)
          When you are ready, click Create and Save.
          </p>
          <p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create Post</a>
          </p>
        </div>
      </div>
      <!--End Top create post bar-->
      <!--Blog posts-->
      {% if blog_posts %}
        {% for post in blog_posts %}
          <div class="blog-post-container">
            {% include 'blog/snippets/blog_post_snippet.html' with blog_post=post %}
          </div>
        {% endfor %}
      {% else %}
        <div class="blog-post-container">
            {% include 'blog/snippets/blog_post_snippet.html' with query=query %}

        </div>
      {% endif %}
      <!--End Blog posts -->
    </div>
    <!--End Blog feed-->

    <!--Right 'create post' column-->
    <div class="right-column col-lg-3 d-lg-flex d-none flex-column">
      <div class="card create-post-bar d-flex flex-column p-3">
        <img class="img-fluid d-block m-auto pb-2" src="{% static 'logo.png' %}" width="72" height="72">
        <p class="lead">
          To write a post:</br>
          Log in to our Website.</br>
          Click the ‘Create Post’ tab.</br>
          Start filling in the blanks: enter your post title in the upper field, and enter your post body content in the main post editing box below it.
          As needed, select a category, add tags, and make other selections from the sections below the post. (Each of these sections is explained below.)
          When you are ready, click Create and Save.


          </p>
          <p class="m-auto"><a class="btn btn-primary" href="{% url 'blog:create' %}">Create Post</a>
          </p>
      </div>
      <div class="card create-post-bar d-flex flex-column p-3">
        <p class="lead">
          On our website you can sell and exchange your goods. if you don't believe you can give it a try.

          </p>
        <img class="img-fluid d-block m-auto pb-2" src="{% static 'olx.png' %}" width="200" height="300">
        <a href="https://www.facebook.com/">Visit our Website</a>

      </div>
      <div class="card create-post-bar d-flex flex-column p-3">
        <p class="lead">
          Your ad can be place
          <a href="http://127.0.0.1:8000/contact_us/"> here </a> !
          </p>

      </div>


    </div>


  </div>
</div>
{% endblock content %}