src/blog/urls.py
from django.urls import path
from blog.views import (
    create_blog_view,
    detail_blog_view,
    # edit_blog_view,

)

app_name = 'blog'

urlpatterns = [
    path('create/', create_blog_view, name="create"),
    path('<slug>/', detail_blog_view, name="detail"),




]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from personal.views import (
    home_screen_view,
)
from account.views import (
    registration_view,
    logout_view,
    login_view,
    account_view,
    must_authenticate_view,

)
from team.views import (
    create_team_view,
    contact_us_view,
)

urlpatterns = [
    path('', home_screen_view, name="home"),
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', 'blog')),
    path('login/', login_view, name="login"),
    path('account/', account_view, name="account"),
    path('logout/', logout_view, name="logout"),
    path('must_authenticate/', must_authenticate_view, name="must_authenticate"),
    path('register/', registration_view, name="register"),
    path('create_team/', create_team_view, name="create_team"),
    path('contact_us/', contact_us_view, name="contact_us"),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.db import models

from django.utils.text import slugify
from django.conf import settings
from django.db.models.signals import post_delete, pre_save
from django.dispatch import receiver

# Create your models here.

def upload_location(instance, filename, **kwargs):
    file_path = 'blog/{author_id}/{title}-{filename}'.format(
        author_id=str(instance.author.id), title=str(instance.title), filename=filename
    )
    return file_path

class BlogPost(models.Model):
    title               = models.CharField(max_length=60, null=False, blank=False)
    body                = models.TextField(max_length=5000, null=False, blank=False)
    image               = models.ImageField(upload_to=upload_location, null=False, blank=False)
    date_published      = models.DateTimeField(auto_now_add=True, verbose_name="date published")
    date_updated        = models.DateTimeField(auto_now=True, verbose_name="date updated")
    author              = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    slug                = models.SlugField(blank=True, unique=True)

    def __str__(self):
        return self.title


@receiver(post_delete, sender=BlogPost)



def submission_delete(sender, instance, **kwargs):
    instance.image.delete(False)

def pre_save_blog_post_receiever(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.author.username + "-" + instance.title)

pre_save.connect(pre_save_blog_post_receiever, sender=BlogPost)

src/blog/forms.py
from django import forms

from blog.models import BlogPost


class CreateBlogPostForm(forms.ModelForm):

    class Meta:
        model = BlogPost
        fields = ['title', 'body', 'image']

src/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.db.models import Q
from blog.models import BlogPost
from blog.forms import CreateBlogPostForm
from account.models import Account

def create_blog_view(request):

    context = {}

    user = request.user
    if not user.is_authenticated:
        return redirect('must_authenticate')

    form = CreateBlogPostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit=False)
        author =  Account.objects.filter(email=user.email).first()
        obj.author = author
        obj.save()
        form = CreateBlogPostForm()

    context['form'] = form

    return render(request, "blog/create_blog.html", context)

def detail_blog_view(request, slug):
    context = {}

    blog_post = get_object_or_404(BlogPost, slug=slug)
    context['blog_post'] = blog_post

    return render(request, 'blog/detail_blog.html', context)


def get_blog_queryset(query=None):
    queryset = []
    queries = query.split(" ") # Django install 2020 = [django, install, 2020]
    for q in queries:
        posts = BlogPost.objects.filter(
            Q(title__icontains=q) |
            Q(body__icontains=q)
        ).distinct()
        for post in posts:
            queryset.append(post)
    return list(set(queryset))

src/blog/templates/blog/create_blog.html
{% extends 'base.html' %}

{% block content %}

    <style type="text/css">
    .container{
    margin-top: 100px;
}
        .create-form{
            width: 100%;
            max-width: 100%;
            padding: 15px;
            margin: auto;
        }
        .submit-button{
            max-width: 200px;
        }

    </style>
    <div class="container">
        <div class="row">
            <div class="col-lg-7 offset-lg-1">
                <form class="create-form" method="post" enctype="multipart/form-data">{% csrf_token %}

                    <div class="form-group">
                        <label for="id_title">Title</label>
                        <input class="form-control" type="text" name="title" id="id_title" placeholder="Title"
                        required autofocus>
                    </div>
                    <div class="form-group">
                        <label for="id_body">Content</label>
                        <textarea class="form-control" rows="10" type="text" name="body" id="id_body" placeholder="Bu yerda nimadir haqida ..." required></textarea>
                    </div>
                    <div class="form-group">
                        <label for="id_image">Image</label>
                        <input type="file" name="image" id="id_image" accept="image/*" required>
                    </div>

                    <button class="submit-button btn btn-lg btn-primary btn-block" type="submit">POST</button>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

src/blog/templates/blog/detail_blog.html
{% extends 'base.html' %}

{% block content %}

<style type="text/css">

    .card {
        max-width: 700px;
    }
    .container{
        padding: 20px;
    }
</style>

<div class="container">
    <div class="row">

        <div class="card m-auto">
            <img class="card-img-top" src="{{blog_post.image.url}}">
            <div class="card-body my-2">
                <h2 class="card-title">{{blog_post.title}}</h2>
                <p class="card-text">{{blog_post.body|safe}}</p>
            </div>

        </div>
    </div>
</div>

{% endblock content %}